#!/bin/sh
# source profile_prjcfg on /etc/init.d/rcS (init script cycle) and /etc/profile (after startup cycle)
source /etc/profile_prjcfg

# fstab devices create
mount -a
echo "
 __  __ ____  _   ___     ______  
|  \/  / ___|| \ | \ \   / /  _ \ 
| |\/| \___ \|  \| |\ \ / /| |_) |
| |  | |___) | |\  | \ V / |  _ < 
|_|  |_|____/|_| \_|  \_/  |_| \_\\ 

"

# To run /etc/init.d/S* script
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ]; then
		echo "[Start] $initscript"
		$initscript
	fi
done
