#
# (C) Copyright 2000-2010
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= lowlevel_init.o
obj-y	+= soc.o
obj-y	+= clock.o
obj-y	+= crypto.o
obj-y	+= nvt-otp.o
obj-$(CONFIG_NVT_FPGA_EMULATION_CA9) += timer.o
obj-$(CONFIG_NVT_BOARD_EVB) += timer.o
