#
# (C) Copyright 2017
# Novatek Microelectronic corp.
#
# SPDX-License-Identifier:	GPL-2.0+
#
ifdef CONFIG_TARGET_NA51055
obj-y += nvt_flash_spi_cmd.o nvt_flash_spi.o
else
obj-y += nvt_flash_spi020_cmd.o nvt_flash_spi020.o
endif
