#!/bin/sh
# Setup mdev
echo "fs" > /proc/nvt_info/bootts
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

# Scan for without insert card
#if [ ! -f /tmp/.nvt_mounts ]; then
#	/etc/mdev-script/autosd.sh
#	rm -rf /tmp/.nvt_mounts;
#fi

KERVER=`cat /proc/version | awk -F'version ' '{print $2}' | awk -F' ' '{print $1}'`
modprobe nvt_pcie_rescan bar_size=0x2000000 bar2_enable=0
modprobe nvt_x86_amp_device_driver
modprobe na51090-clk-ep-common
modprobe nvme
modprobe ehci-hcd
modprobe xhci-plat-hcd
modprobe ahci-nvt-ivot
echo "fs" > /proc/nvt_info/bootts
