#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
#for initscript in /etc/init.d/S[0-9][0-9]*
#do
#	if [ -x $initscript ] ;
#	then
#		echo "[RCS]: $initscript"
#		$initscript
#	fi
#done

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

#bruce.milesight add 2014-8-7 17:03:50
if [ -f /mnt/nand/add.sh ]; then
	echo "Exist add.sh run..."
	chmod +x /mnt/nand/add.sh
	/mnt/nand/add.sh &
fi
#end add 2014-8-7 17:03:50
