#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
KBUILD_CFLAGS := -fno-builtin -Wall -Werror -Iboard/$(BOARDDIR)/../common/include
obj-$(CONFIG_NVT_DDR_SCAN) += nvt_ddr_scan.o


