#!/bin/sh


#cfg_mem()
#{
#	var0=`cat /proc/cmdline | grep 'mem=256M'`
#	if [ "$var0" != "" ]; then
#		echo "cmdline: mem=256M, total mem is 512M"
#		load3516a -i -allmem 512 -osmem 256 -offline
#	else
#		echo "cmdline: mem=128M, total mem is 256M"
#		load3516a -i -allmem 256 -osmem 128 -offline
#	fi	
#}

#echo "Began to unpack /opt/app ..."
#tar -jxf /home/app.tar.bz2 -C /opt
#echo "unpack Done"

source /etc/profile
cur_dir=$(pwd)

cd /usr/local/bin/

sh /usr/local/bin/load626v100 -i

cd $cur_dir

fsck.ext4 -pf /dev/mmcblk0p8
mount -t ext4 /dev/mmcblk0p8 /mnt/nand
ret=$?
echo “ret=$ret”
if [ $ret -ne 0 ];then
	echo "Start format /dev/mmcblk0p8"
	mkfs.ext4 -F /dev/mmcblk0p8
	mount -t ext4 /dev/mmcblk0p8 /mnt/nand
	echo "Format & mount /dev/mmcblk0p8 success"
fi

fsck.ext4 -pf /dev/mmcblk0p9
mount -t ext4 /dev/mmcblk0p9 /mnt/nand2
ret=$?
echo “ret=$ret”
if [ $ret -ne 0 ];then
	echo "Start format /dev/mmcblk0p9"
	mkfs.ext4 -F /dev/mmcblk0p9
	mount -t ext4 /dev/mmcblk0p9 /mnt/nand2
	echo "Format & mount /dev/mmcblk0p9 success"
fi

fsck.ext4 -pf /dev/mmcblk0p10
mount -t ext4 /dev/mmcblk0p10 /mnt/nand3
ret=$?
echo “ret=$ret”
if [ $ret -ne 0 ];then
	echo "Start format /dev/mmcblk0p10"
	mkfs.ext4 -F /dev/mmcblk0p10
	mount -t ext4 /dev/mmcblk0p10 /mnt/nand3
	echo "Format & mount /dev/mmcblk0p10 success"
fi

#source /etc/profile

#cfg_mem

daemon & 

#msserver &

/opt/app/start_app.sh &
