######################################################################
## Filename:      mscrypt.makefile
## Author:        yun
## Created at:    2018-09-06
##                
## Description:   编译mscrypt
##               
## Copyright (C)  milesight
##                
######################################################################
#需要包含的目录
INCLUDE         := -I$(PUBLIC_INC_DIR) 
#需要的lib库
LDFLAGS         := -L$(PUBLIC_LIB_DIR) -lm -lmsstd
#目标类型("exe"-生成可执行文件 "so"-生成动态库 "a"-生成静态库)
TARGET_TYPE:="so"


#导入通用mk文件
include $(BUILD_COMMON_MK)

    
